title:             thammuio
email:             surinuthalapati@gmail.com
description:       Technology Blog.
author:            thammuio
baseurl:           "/"
url:               "https://thammuio.github.io"

# Social Profiles
twitter_username:  thammuio
github_username:   thammuio
facebook_username: thammuio

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
